version: "3.9"
services:
  api:
    build: .
    image: apioqr:latest
    container_name: apiocr
    ports:
      - "5250:5250"
    environment:
      - FLASK_APP=app.py
    volumes:
      - .:/app:ro
